// ebook_web_page.h
// 书籍/字体管理网页（内联 HTML/CSS/JS 单常量）。上传/删除 /sdcard/books 下的
// .txt / .epub 书籍与 .ttf / .otf 阅读字体（列表按 type 分「书架」「字体」两组）。
// 上传用 XHR 把文件原始字节 POST 到 /api/upload?name=，带进度。Claude.ai 风深色主题。

#ifndef EBOOK_WEB_PAGE_H
#define EBOOK_WEB_PAGE_H

namespace ebook_web_page {

inline const char* Html() {
    return
        "<!DOCTYPE html><html lang='zh'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        "<title>书籍管理</title><style>"
        "*{box-sizing:border-box}"
        "body{margin:0;padding:20px;font-family:-apple-system,system-ui,sans-serif;"
        "background:#0e1116;color:#e6e6e6;max-width:640px;margin:0 auto}"
        "h1{font-size:22px;margin:8px 0}"
        ".sub{color:#8b93a1;font-size:13px;margin:4px 0 16px}"
        ".card{background:#161b22;border:1px solid #263041;border-radius:12px;"
        "padding:16px;margin-bottom:16px}"
        ".drop{border:2px dashed #2f4058;border-radius:12px;padding:26px 16px;text-align:center;"
        "color:#8b93a1;font-size:14px;cursor:pointer}"
        ".drop.hot{border-color:#2f6f52;color:#cfe;background:#111b16}"
        "ul{list-style:none;margin:0;padding:0}"
        "li{display:flex;align-items:center;gap:10px;padding:11px 0;"
        "border-bottom:1px solid #21262d}li:last-child{border-bottom:0}"
        ".meta{flex:1;min-width:0}"
        ".name{font-size:15px;word-break:break-all}"
        ".sz{color:#8b93a1;font-size:12px;margin-top:2px}"
        "button{background:#263041;color:#e6e6e6;border:0;border-radius:8px;"
        "padding:8px 14px;font-size:14px;cursor:pointer}"
        "button.del{color:#ff6b6b}button:disabled{opacity:.4}"
        ".prog{height:6px;background:#0e1116;border-radius:4px;overflow:hidden;margin-top:10px;display:none}"
        ".prog.on{display:block}.bar{height:100%;width:0;background:#2f6f52;transition:.1s}"
        ".pf{font-size:12px;color:#8b93a1;margin-top:6px;min-height:16px}"
        ".empty{color:#8b93a1;padding:12px 0}"
        ".toast{position:fixed;left:50%;bottom:24px;transform:translateX(-50%);"
        "background:#2f6f52;color:#fff;padding:10px 18px;border-radius:20px;"
        "opacity:0;transition:.2s;pointer-events:none;max-width:80%}"
        ".toast.show{opacity:1}.toast.err{background:#a33}"
        "</style></head><body>"
        "<h1>书籍 / 字体管理</h1>"
        "<p class='sub'>上传 / 删除 SD 卡里的 TXT / EPUB 书籍，以及 TTF / OTF 阅读字体。"
        "上传后在设备上返回书架 / 阅读菜单即可看到。</p>"
        "<div class='card'>"
        "<div id='drop' class='drop'>点此选择 .txt / .epub / .ttf / .otf 文件，或拖拽到这里上传<br>（可多选）</div>"
        "<input id='fi' type='file' accept='.txt,.epub,.ttf,.otf' multiple style='display:none'>"
        "<div id='prog' class='prog'><div id='bar' class='bar'></div></div>"
        "<div id='pf' class='pf'></div>"
        "</div>"
        "<div class='card'><h2 style='font-size:16px;margin:0 0 10px'>书架</h2>"
        "<ul id='list'></ul><div id='empty' class='empty' style='display:none'>暂无书籍</div></div>"
        "<div class='card'><h2 style='font-size:16px;margin:0 0 10px'>字体</h2>"
        "<ul id='flist'></ul><div id='fempty' class='empty' style='display:none'>暂无字体</div></div>"
        "<div id='toast' class='toast'></div>"
        "<script>"
        "var listEl=document.getElementById('list'),emptyEl=document.getElementById('empty');"
        "var flistEl=document.getElementById('flist'),femptyEl=document.getElementById('fempty');"
        "var fi=document.getElementById('fi'),drop=document.getElementById('drop');"
        "var prog=document.getElementById('prog'),bar=document.getElementById('bar'),pf=document.getElementById('pf');"
        "function toast(m,e){var t=document.getElementById('toast');t.textContent=m;"
        "t.className='toast show'+(e?' err':'');setTimeout(function(){t.className='toast'+(e?' err':'')},2200);}"
        "function fmt(n){if(n>=1048576)return(n/1048576).toFixed(2)+' MB';"
        "if(n>=1024)return(n/1024).toFixed(1)+' KB';return n+' B';}"
        "function row(b,ul){var li=document.createElement('li');"
        "var m=document.createElement('div');m.className='meta';"
        "var nm=document.createElement('div');nm.className='name';nm.textContent=b.name;"
        "var sz=document.createElement('div');sz.className='sz';sz.textContent=fmt(b.size);"
        "m.appendChild(nm);m.appendChild(sz);"
        "var db=document.createElement('button');db.className='del';db.textContent='删除';"
        "db.onclick=function(){del(b.name)};"
        "li.appendChild(m);li.appendChild(db);ul.appendChild(li);}"
        "function load(){fetch('/api/list').then(function(r){return r.json()}).then(function(a){"
        "listEl.innerHTML='';flistEl.innerHTML='';var nb=0,nf=0;"
        "a.forEach(function(b){if(b.type==='font'){nf++;row(b,flistEl);}else{nb++;row(b,listEl);}});"
        "emptyEl.style.display=nb?'none':'block';femptyEl.style.display=nf?'none':'block';"
        "}).catch(function(){toast('读取列表失败',1)});}"
        "function del(name){if(!confirm('删除 '+name+' ？'))return;"
        "fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},"
        "body:'name='+encodeURIComponent(name)}).then(function(r){"
        "if(r.status===200){toast('已删除');load();}else{r.text().then(function(t){toast(t||'删除失败',1)});}"
        "}).catch(function(){toast('删除失败',1)});}"
        "function up(file,cb){var xhr=new XMLHttpRequest();"
        "xhr.open('POST','/api/upload?name='+encodeURIComponent(file.name));"
        "xhr.upload.onprogress=function(e){if(e.lengthComputable){bar.style.width=(e.loaded/e.total*100)+'%';}};"
        "xhr.onload=function(){cb(xhr.status===200,xhr.responseText)};"
        "xhr.onerror=function(){cb(false,'网络错误')};xhr.send(file);}"
        "function upAll(files){var arr=[];for(var i=0;i<files.length;i++){"
        "var f=files[i];if(/\\.(txt|epub|ttf|otf)$/i.test(f.name))arr.push(f);}"
        "if(!arr.length){toast('请选择 .txt / .epub / .ttf / .otf 文件',1);return;}"
        "prog.className='prog on';var idx=0;"
        "function next(){if(idx>=arr.length){prog.className='prog';bar.style.width='0';pf.textContent='';"
        "toast('上传完成');load();return;}var f=arr[idx];pf.textContent='上传中 ('+(idx+1)+'/'+arr.length+')：'+f.name;"
        "bar.style.width='0';up(f,function(ok,msg){if(!ok){toast(f.name+'：'+(msg||'失败'),1);}idx++;next();});}"
        "next();}"
        "drop.onclick=function(){fi.click()};"
        "fi.onchange=function(){if(fi.files.length)upAll(fi.files);fi.value='';};"
        "drop.ondragover=function(e){e.preventDefault();drop.className='drop hot'};"
        "drop.ondragleave=function(){drop.className='drop'};"
        "drop.ondrop=function(e){e.preventDefault();drop.className='drop';if(e.dataTransfer.files.length)upAll(e.dataTransfer.files);};"
        "load();"
        "</script></body></html>";
}

}  // namespace ebook_web_page

#endif  // EBOOK_WEB_PAGE_H
